### ISSUE TITLE
get the video stream of the sender in the remote side

### ISSUE THREAD

**Issue by logg926** [logg926/audioProRemote#1]
angular tutorial:

https://www.youtube.com/watch?v=htPYk6QxacQ&ab_channel=Academind

Vonage Video Api :

go through getting start and the code i have see what it does

https://tokbox.com/developer/

Task:
get MediaStream of the sender from receiving end.

Tip:
"I think he has to render remote stream to a <video> element and then call captureStream() on <video> to get a stream and then call getAudioTracks() to get the audio track. If it is a one-one, yes he can post process at source and then send it, but for whatever reasons if he wants to do on receiving side he can use logic above."

Opentok=> canvas => capture to captureStream()

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream

Possible solution: 

If u finish: 
Audioworklet for postprocessing

**Comment by XDMickeyYau** [comment]
- [ ] new branh
- [ ] get link btw html component
